/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import Logger from "../../../utils/logger";

// Fallback component if Room fails to load
const RoomFallback = () => (
  <group>
    <mesh position={[0, -1, 0]}>
      <boxGeometry args={[8, 0.2, 8]} />
      <meshStandardMaterial color="#333" />
    </mesh>
    <mesh position={[0, 1, 0]}>
      <boxGeometry args={[2, 2, 0.2]} />
      <meshStandardMaterial color="#444" emissive="#112233" emissiveIntensity={0.5} />
    </mesh>
  </group>
);

export function Room({ screensRef: externalScreensRef, ...props }) {
  const [hasError, setHasError] = useState(false);
  const internalScreensRef = useRef();
  const screensRef = externalScreensRef || internalScreensRef;

  // Always call hooks first - never conditionally
  const gltf = useGLTF("/models/optimized-room.glb");
  const matcapTexture = useTexture("/images/textures/mat1.png");

  // Check if we have the required data
  const nodes = gltf?.nodes;
  const materials = gltf?.materials;

  // Use useEffect to handle validation and error setting
  useEffect(() => {
    if (!nodes || !materials) {
      Logger.error('Room model nodes or materials not found');
      setHasError(true);
    } else {
      setHasError(false);
    }
  }, [nodes, materials]);

  // If we don't have nodes/materials or there's an error, render fallback
  if (hasError || !nodes || !materials) {
    return <RoomFallback />;
  }

  // Ensure materials are available before creating new ones
  const curtainMaterial = new THREE.MeshPhongMaterial({
    color: "#d90429",
  });

  const bodyMaterial = new THREE.MeshPhongMaterial({
    map: matcapTexture || null,
  });

  const tableMaterial = new THREE.MeshPhongMaterial({
    color: "#582f0e",
  });

  const radiatorMaterial = new THREE.MeshPhongMaterial({
    color: "#fff",
  });

  const compMaterial = new THREE.MeshStandardMaterial({
    color: "#fff",
  });

  const pillowMaterial = new THREE.MeshPhongMaterial({
    color: "#8338ec",
  });

  const chairMaterial = new THREE.MeshPhongMaterial({
    color: "#000",
  });

  // Enhanced screen material with emissive glow to compensate for missing bloom
  const screenMaterial = new THREE.MeshStandardMaterial({
    color: "#ffffff",
    emissive: "#3366ff",
    emissiveIntensity: 0.5,
    transparent: true,
    opacity: 0.9,
  });

  // Helper function to safely access node geometry
  const getNodeGeometry = (nodePath) => {
    try {
      const pathParts = nodePath.split('.');
      let node = nodes;
      for (const part of pathParts) {
        node = node?.[part];
      }
      return node?.geometry || null;
    } catch (error) {
      Logger.warn(`Could not access node: ${nodePath}`);
      return null;
    }
  };

  // Helper function to safely access material
  const getMaterial = (materialName) => {
    try {
      return materials?.[materialName] || new THREE.MeshStandardMaterial({ color: "#666" });
    } catch (error) {
      Logger.warn(`Could not access material: ${materialName}`);
      return new THREE.MeshStandardMaterial({ color: "#666" });
    }
  };

  // If we have an error state, render fallback
  if (hasError) {
    return <RoomFallback />;
  }

  return (
    <group {...props} dispose={null}>
      {getNodeGeometry("_________6_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("_________6_blinn1_0")}
          material={curtainMaterial}
        />
      )}
      {getNodeGeometry("body1_blinn1_0") && (
        <mesh 
          geometry={getNodeGeometry("body1_blinn1_0")} 
          material={bodyMaterial} 
        />
      )}
      {getNodeGeometry("cabin_blinn1_0") && (
        <mesh 
          geometry={getNodeGeometry("cabin_blinn1_0")} 
          material={tableMaterial} 
        />
      )}
      {getNodeGeometry("chair_body_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("chair_body_blinn1_0")}
          material={chairMaterial}
        />
      )}
      {getNodeGeometry("comp_blinn1_0") && (
        <mesh 
          geometry={getNodeGeometry("comp_blinn1_0")} 
          material={compMaterial} 
        />
      )}
      {getNodeGeometry("emis_lambert1_0") && (
        <mesh
          ref={screensRef}
          geometry={getNodeGeometry("emis_lambert1_0")}
          material={screenMaterial}
        />
      )}
      {getNodeGeometry("handls_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("handls_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("keyboard_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("keyboard_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("kovrik_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("kovrik_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("lamp_bl_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("lamp_bl_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("lamp_white_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("lamp_white_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("miuse_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("miuse_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("monitor2_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("monitor2_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("monitor3_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("monitor3_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("pCylinder5_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("pCylinder5_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("pillows_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("pillows_blinn1_0")}
          material={pillowMaterial}
        />
      )}
      {getNodeGeometry("polySurface53_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("polySurface53_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("radiator_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("radiator_blinn1_0")}
          material={radiatorMaterial}
        />
      )}
      {getNodeGeometry("radiator_blinn1_0001") && (
        <mesh
          geometry={getNodeGeometry("radiator_blinn1_0001")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("railing_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("railing_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("red_bttns_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("red_bttns_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("red_vac_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("red_vac_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("stylus_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("stylus_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("table_blinn1_0") && (
        <mesh 
          geometry={getNodeGeometry("table_blinn1_0")} 
          material={tableMaterial} 
        />
      )}
      {getNodeGeometry("tablet_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("tablet_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("triangle_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("triangle_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("vac_black_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("vac_black_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("vacuum1_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("vacuum1_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("vacuumgrey_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("vacuumgrey_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("vires_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("vires_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("window_blinn1_0") && (
        <mesh
          geometry={getNodeGeometry("window_blinn1_0")}
          material={getMaterial("blinn1")}
        />
      )}
      {getNodeGeometry("window4_phong1_0") && (
        <mesh
          geometry={getNodeGeometry("window4_phong1_0")}
          material={getMaterial("phong1")}
        />
      )}
    </group>
  );
}

useGLTF.preload("/models/optimized-room.glb");
